---
  - name: create rdma hostfile
    template:
      src: templates/hostfile_rdma.j2
      dest: /etc/opt/oci-hpc/hostfile.rdma
      mode: '0644'
      owner: opc
      group: opc
    tags: hostfile
    delegate_to: 127.0.0.1
    run_once: true
  - name: create tcp hostfile
    template:
      src: templates/hostfile_tcp.j2
      dest: /etc/opt/oci-hpc/hostfile.tcp
      mode: '0644'
      owner: opc
      group: opc
    tags: hostfile
    delegate_to: 127.0.0.1
    run_once: true
